builtin-extend: Add missing include
Fixes the following build breakage on Linux:

  CC       builtin-extend.o
builtin-extend.c: In function ‘cmd_extend’:
builtin-extend.c:181: error: ‘errno’ undeclared (first use in this function)
builtin-extend.c:181: error: (Each undeclared identifier is reported only once
builtin-extend.c:181: error: for each function it appears in.)

Signed-off-by: Pekka Enberg <penberg@kernel.org>